networks:
    local-net:
        driver: bridge

services:
  nginx:
    image: ${DOCKER_REGISTRY-}noteapp/nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - local-net
    ports:
      - 80:80

  frontend:
    image: ${DOCKER_REGISTRY-}noteapp/frontend
    build:
      context: frontend
      dockerfile: Dockerfile.deployment
    environment:
      NODE_ENV: production
    networks:
      - local-net

  backend:
    image: ${DOCKER_REGISTRY-}noteapp/backend
    depends_on:
      - database
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - local-net
    environment:
      ConnectionStrings__DefaultConnection: Data Source=sql_server2022;Initial Catalog=NoteAppDb;User Id=SA;Password=Password123;MultipleActiveResultSets=true;Encrypt=False
      Jwt__Key: <randomKeyAtLeast128CharLongForExampleKRtUr30X3F3F173B63IEN9RCsNc6OnxPj6BT5rjEwTinRjvxIg>
      Jwt__ValidMinutes: 60
      Jwt__Issuer: https://localhost:44345/
      Jwt__Audience: https://localhost:44345/
      WebClient: http://localhost:3000
      EmailSettings__Sender: <sender>
      EmailSettings__Username: <username>
      EmailSettings__Password: <password>
      EmailSettings__Host: <host>
      EmailSettings__Port: 587
    
  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password123" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - local-net