version: '3.4'

services:
  
  backend:
    image: ${DOCKER_REGISTRY-}noteapp/backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5062:80"
      - "5025:443"
    environment:
      ConnectionStrings__DefaultConnection: Data Source=sql_server2022;Initial Catalog=NoteAppDb;User Id=SA;Password=Password123;MultipleActiveResultSets=true;Encrypt=False
  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password123" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  frontend:
    image: ${DOCKER_REGISTRY-}noteapp/frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  